"""Generate docs that must never drift from code.

    python -m app.docs_gen            # writes ../docs/CALCULATIONS.md, ../docs/API.md, ../CITATION.cff
    python -m app.docs_gen --check    # exit 1 if any committed file is stale (used by tests/CI)
"""
from __future__ import annotations

import sys
from pathlib import Path

from fastapi.routing import APIRoute

from .config import PRODUCT_ROOT
from .services.briefs import citation_cff, methodology_markdown

CALC_INTRO = """<!-- GENERATED by `python -m app.docs_gen` from backend/app/calculations — do not edit by hand. -->

> Every calculation in OpenDMO is a registered, versioned, documented, pure
> function with known-value verification cases that run as unit tests
> (`backend/tests/test_calculations.py`). Composite indices marked
> **screening indicator** are transparent prioritisation tools — not
> certifications, accreditations or regulatory determinations.
> No equation lives in the React frontend.

"""


def calculations_md() -> str:
    return CALC_INTRO + methodology_markdown()


def api_md() -> str:
    from .main import app
    rows = []
    for r in app.routes:
        if not isinstance(r, APIRoute) or not r.include_in_schema:
            continue
        doc = (r.endpoint.__doc__ or '').strip().splitlines()
        desc = doc[0] if doc else r.name.replace('_', ' ')
        for m in sorted(r.methods - {'HEAD', 'OPTIONS'}):
            rows.append((r.path, m, desc, r.tags[0] if r.tags else ''))
    groups: dict[str, list] = {}
    for path, m, desc, _ in rows:
        seg = path.split('/')[2] if path.count('/') >= 2 else path
        groups.setdefault(seg, []).append((m, path, desc))
    out = ['<!-- GENERATED by `python -m app.docs_gen` from the FastAPI routes — do not edit by hand. -->', '',
           '# OpenDMO API', '',
           'Base URL: the same origin as the UI (default `http://127.0.0.1:8000`). All endpoints are under `/api`, '
           'return JSON unless noted, and are local-only by default. The machine-readable schema is at '
           '`/api/openapi.json` (the interactive Swagger page is disabled because it loads assets from a CDN).', '',
           'Errors: `422` with `{"detail": "..."}` for validation problems, `404` for unknown ids or routes, `409` for '
           'conflicts (e.g. archived datasets).', '']
    for g in sorted(groups):
        out += [f'## `{g}`', '', '| Method | Path | Purpose |', '|---|---|---|']
        out += [f'| {m} | `{p}` | {d} |' for m, p, d in sorted(groups[g], key=lambda x: (x[1], x[0]))]
        out.append('')
    return '\n'.join(out)


TARGETS = {
    PRODUCT_ROOT / 'docs' / 'CALCULATIONS.md': calculations_md,
    PRODUCT_ROOT / 'docs' / 'API.md': api_md,
    PRODUCT_ROOT / 'CITATION.cff': citation_cff,
}


def main(check: bool = False) -> int:
    stale = []
    for path, fn in TARGETS.items():
        text = fn()
        if check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8')
            print(f'wrote {path}')
    if stale:
        print('stale generated docs (run `python -m app.docs_gen`):\n  ' + '\n  '.join(stale))
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main('--check' in sys.argv))
