"""Write the bundled sample CSVs (DEMO data) used by the docs and the import tutorial.

    python -m app.seed.samples ../samples
"""
from __future__ import annotations

import sys
from pathlib import Path

from ..services.csv_import import observations_csv
from .packs import generate

README = """# Sample CSVs (DEMO — synthetic)

Every file here is generated by `backend/app/seed/samples.py` from the OpenDMO
seed-pack generator. Values are synthetic and must not be cited as findings.

| File | Layout | Use with dataset type |
|---|---|---|
| DEMO_jaflong_visitor_flow_wide.csv | wide (one column per variable) | Visitor flow & crowding |
| DEMO_sajek_weather_long.csv | long (period, variable, value, unit, quality_flag) | Weather & hydrology observations |
| DEMO_bandarban_economy_wide.csv | wide, yearly | Tourism economy & leakage |
| DEMO_ratargul_sentiment_long.csv | long, quarterly | Community sentiment survey |
| DEMO_messy_gate_counts.csv | semicolon, `Mon YYYY` dates, comma decimals, one bad value | practise the wizard (choose decimal “,”) |
"""

MESSY = """Month;Visitor Count;Peak day;Hotel occupancy
Jan 2025;52 340;6 120;61,5
Feb 2025;49 870;5 940;58,0
Mar 2025;41 205;5 010;n/a
Apr 2025;37 990;4 780;47,25
May 2025;30 112;oops;41,0
Jun 2025;22 450;2 990;33,5
"""


def write_samples(out: Path) -> list[Path]:
    out.mkdir(parents=True, exist_ok=True)
    files = []
    specs = [('jaflong', 'visitor_flow', 'wide', 'DEMO_jaflong_visitor_flow_wide.csv'),
             ('sajek', 'weather', 'long', 'DEMO_sajek_weather_long.csv'),
             ('bandarban', 'economy', 'wide', 'DEMO_bandarban_economy_wide.csv'),
             ('ratargul', 'community_sentiment', 'long', 'DEMO_ratargul_sentiment_long.csv')]
    for dest, kind, layout, name in specs:
        rows = [dict(r, quality_flag='ok') for r in generate(dest)[kind]]
        p = out / name
        p.write_text(observations_csv(rows, layout), encoding='utf-8', newline='')
        files.append(p)
    (out / 'DEMO_messy_gate_counts.csv').write_text(MESSY, encoding='utf-8', newline='')
    (out / 'README.md').write_text(README, encoding='utf-8')
    return files + [out / 'DEMO_messy_gate_counts.csv', out / 'README.md']


if __name__ == '__main__':
    for f in write_samples(Path(sys.argv[1] if len(sys.argv) > 1 else '../samples')):
        print(f)
